name: Osx

on:
  workflow_dispatch:

jobs:
  build_Osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run : brew update
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_EZ_LIBS_TESTING=ON -DUSE_EZ_EXPR_PERFOS_GENERATION=ON
    - name: build
      run: cmake --build build
    - name: ctest
      run: ctest --test-dir build --output-on-failure
    - name: zip test results
      if: always()
      run: zip ./tests_results.zip ./TestResults -r
    - name: upload test results artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests_results_osx.zip
        path: ./tests_results.zip
